### ISSUE TITLE
Implement Header Component

### ISSUE THREAD

**Issue by zhunan123** [GayaHealth/Gaya_Website#11]
Need to implement header component.
which should includes 
- a Gaya icon on the top left corner, 
- Nav bar to navigate through each components: Shop, Ingredients, About, Blog
- a join waitlist button

![1687901217480](https://github.com/GayaHealth/Gaya_Website/assets/47227727/517d7e97-379c-4f97-9777-d746304ae044)

**Comment by lawrenceslng** [comment]
Since we're using Material UI, I'm thinking for the links to different pages we can use this:
https://mui.com/material-ui/react-app-bar/#app-bar-with-responsive-menu

So that the header is responsive for different devices, what do you guys think?

Questions: 
1) if we do this, when the links to different pages are collapsed, should the "Join Waitlist" button be within the collapsed menu as well as a regular item?
2) Should the logo be an image or should we write and style it using HTML and CSS?

**Comment by zhunan123** [comment]
> 

Nice research! I think Material UI is pretty solid for responsive pages, we can definitely use this. 
As for your questions,

- 1) Do you mean like when we navigate to different links, we should collapse the app bar header? 
- 2) I think probably we should use a image or a designed icon in this case.

**Comment by zhunan123** [comment]
> 

Sounds good, thanks for updating that. I will start working on this ticket.

**Comment by zhunan123** [comment]
> So we have confirmation now, the header component will look like so:
> 
> <img alt="image" width="993" src="https://user-images.githubusercontent.com/38678774/249857239-e9931978-5342-4eec-a466-d1b6b3eb8182.png">
> When viewed on smaller devices, the menu will collapse into a hamburger menu, and `Join Waitlist` will NOT be on it.
> 
> The logo we can use the one in the shared Google Drive

Sounds good, thanks for updating that. I will start working on this ticket.

**Comment by zhunan123** [comment]
I have raised the PR, now is ready for review: https://github.com/GayaHealth/Gaya_Website/pull/19
